name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Build run-pmsa003i
      run: go build -v ./cmd/run-pmsa003i

    - name: Build run-sgp30
      run: go build -v ./cmd/run-sgp30
